"""Dependency registry bootstrap helpers for the governed HTTP server.

Purpose: isolate platform construction and dependency group registration from
the main server module.
Governance scope: [OCE, CDCV, CQTE, UWMA]
Dependencies: governed session platform, dependency wiring, and dependency
group registration helpers.
Invariants:
  - Platform bootstrap warnings remain bounded and deterministic.
  - Runtime dependency wiring keeps the same scheduler, connector, sandbox,
    and explanation bindings.
  - Dependency group keys remain stable for router resolution.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Mapping

from mcoi_runtime.app.server_deps import (
    register_dependency_groups,
    wire_runtime_dependencies,
)
from mcoi_runtime.core.governed_session import Platform as GovernedPlatform


@dataclass(frozen=True)
class DependencyRegistryBootstrap:
    """Dependency registry bootstrap result."""

    platform: Any


def bootstrap_dependency_registry(
    *,
    deps_container: Any,
    clock: Callable[[], str],
    env: str,
    surface: Any,
    store: Any,
    llm_bridge: Any,
    llm_bootstrap_result: Any,
    llm_circuit: Any,
    streaming_adapter: Any,
    model_router: Any,
    metrics: Any,
    rate_limiter: Any,
    rate_limit_headers: Any,
    guard_chain: Any,
    audit_trail: Any,
    input_validator: Any,
    proof_bridge: Any,
    pii_scanner: Any,
    content_safety_chain: Any,
    tenant_gating: Any,
    field_encryption_bootstrap: Mapping[str, Any],
    tenant_budget_mgr: Any,
    tenant_ledger: Any,
    tenant_isolation: Any,
    tenant_quota: Any,
    tenant_partitions: Any,
    tenant_analytics: Any,
    usage_reporter: Any,
    isolation_verifier: Any,
    agent_registry: Any,
    task_manager: Any,
    workflow_engine: Any,
    traced_workflow: Any,
    replay_recorder: Any,
    chat_workflow: Any,
    agent_chain: Any,
    agent_orchestrator: Any,
    coordination_engine: Any,
    coordination_store: Any,
    scheduler: Any,
    connector_framework: Any,
    access_runtime: Any,
    policy_sandbox: Any,
    runbook_learning: Any,
    explanation_engine: Any,
    knowledge_graph: Any,
    audit_anchor: Any,
    tool_registry: Any,
    tool_agent: Any,
    agent_memory: Any,
    task_queue: Any,
    batch_pipeline: Any,
    wf_templates: Any,
    semantic_search: Any,
    conversation_store: Any,
    prompt_engine: Any,
    schema_validator: Any,
    state_persistence: Any,
    structured_output: Any,
    cost_analytics: Any,
    deep_health: Any,
    health_agg: Any,
    health_agg_v2: Any,
    health_v3: Any,
    certifier: Any,
    cert_daemon: Any,
    event_bus: Any,
    event_store: Any,
    webhook_manager: Any,
    webhook_retry: Any,
    config_manager: Any,
    config_watcher: Any,
    config_drift: Any,
    observability: Any,
    plugin_registry: Any,
    api_versions: Any,
    platform_logger: Any,
    api_key_mgr: Any,
    data_export: Any,
    sla_monitor: Any,
    notification_dispatcher: Any,
    prom_exporter: Any,
    grafana_dashboard: Any,
    request_tracer: Any,
    monitor: Any,
    shutdown_mgr: Any,
    correlation_mgr: Any,
    idempotency_store: Any,
    response_compressor: Any,
    canary_controller: Any,
    secret_rotation: Any,
    request_dedup: Any,
    snapshot_mgr: Any,
    otel_exporter: Any,
    circuit_dashboard: Any,
    deploy_checker: Any,
    api_migration: Any,
    retry_engine: Any,
    region_router: Any,
    request_ctx_factory: Any,
    governed_cache: Any,
    feature_flags: Any,
    dep_graph: Any,
    backpressure: Any,
    ab_engine: Any,
    platform_cls: type[Any] = GovernedPlatform,
    wire_runtime_dependencies_fn: Callable[..., Any] = wire_runtime_dependencies,
    register_dependency_groups_fn: Callable[..., Any] = register_dependency_groups,
) -> DependencyRegistryBootstrap:
    """Build the platform harness and register dependency groups."""
    platform = platform_cls(
        clock=clock,
        access_runtime=access_runtime,
        content_safety_chain=content_safety_chain,
        pii_scanner=pii_scanner,
        budget_mgr=tenant_budget_mgr,
        llm_bridge=llm_bridge,
        audit_trail=audit_trail,
        proof_bridge=proof_bridge,
        tenant_gating=tenant_gating,
        rate_limiter=rate_limiter,
        bootstrap_warnings=tuple(
            warning
            for warning in (field_encryption_bootstrap.get("warning", ""),)
            if warning
        ),
        bootstrap_components={
            "access_runtime": access_runtime is not None,
            "llm_bridge": llm_bridge is not None,
            "tenant_gating": tenant_gating is not None,
            "proof_bridge": proof_bridge is not None,
            "field_encryption": bool(field_encryption_bootstrap.get("enabled", False)),
        },
    )

    wire_runtime_dependencies_fn(
        guard_chain=guard_chain,
        audit_trail=audit_trail,
        scheduler=scheduler,
        connector_framework=connector_framework,
        policy_sandbox=policy_sandbox,
        explanation_engine=explanation_engine,
    )

    register_dependency_groups_fn(
        deps_container,
        {
            "surface": surface,
            "store": store,
            "_clock": clock,
            "ENV": env,
        },
        {
            "llm_bridge": llm_bridge,
            "llm_bootstrap_result": llm_bootstrap_result,
            "llm_circuit": llm_circuit,
            "streaming_adapter": streaming_adapter,
            "model_router": model_router,
        },
        {
            "metrics": metrics,
            "rate_limiter": rate_limiter,
            "rate_limit_headers": rate_limit_headers,
            "guard_chain": guard_chain,
            "audit_trail": audit_trail,
            "input_validator": input_validator,
            "proof_bridge": proof_bridge,
            "pii_scanner": pii_scanner,
            "content_safety_chain": content_safety_chain,
            "tenant_gating": tenant_gating,
            "field_encryption_bootstrap": dict(field_encryption_bootstrap),
            "platform": platform,
        },
        {
            "tenant_budget_mgr": tenant_budget_mgr,
            "tenant_ledger": tenant_ledger,
            "tenant_isolation": tenant_isolation,
            "tenant_quota": tenant_quota,
            "tenant_partitions": tenant_partitions,
            "tenant_analytics": tenant_analytics,
            "usage_reporter": usage_reporter,
            "isolation_verifier": isolation_verifier,
        },
        {
            "agent_registry": agent_registry,
            "task_manager": task_manager,
            "workflow_engine": workflow_engine,
            "traced_workflow": traced_workflow,
            "replay_recorder": replay_recorder,
            "chat_workflow": chat_workflow,
            "agent_chain": agent_chain,
            "agent_orchestrator": agent_orchestrator,
            "coordination_engine": coordination_engine,
            "coordination_store": coordination_store,
            "scheduler": scheduler,
            "connector_framework": connector_framework,
            "access_runtime": access_runtime,
            "policy_sandbox": policy_sandbox,
            "runbook_learning": runbook_learning,
            "explanation_engine": explanation_engine,
            "knowledge_graph": knowledge_graph,
            "audit_anchor": audit_anchor,
            "tool_registry": tool_registry,
            "tool_agent": tool_agent,
            "agent_memory": agent_memory,
            "task_queue": task_queue,
            "batch_pipeline": batch_pipeline,
            "wf_templates": wf_templates,
            "semantic_search": semantic_search,
        },
        {
            "conversation_store": conversation_store,
            "prompt_engine": prompt_engine,
            "schema_validator": schema_validator,
        },
        {
            "state_persistence": state_persistence,
            "structured_output": structured_output,
            "cost_analytics": cost_analytics,
        },
        {
            "deep_health": deep_health,
            "health_agg": health_agg,
            "health_agg_v2": health_agg_v2,
            "health_v3": health_v3,
            "certifier": certifier,
            "cert_daemon": cert_daemon,
        },
        {
            "event_bus": event_bus,
            "event_store": event_store,
            "webhook_manager": webhook_manager,
            "webhook_retry": webhook_retry,
        },
        {
            "config_manager": config_manager,
            "config_watcher": config_watcher,
            "config_drift": config_drift,
            "observability": observability,
            "plugin_registry": plugin_registry,
            "api_versions": api_versions,
            "platform_logger": platform_logger,
            "api_key_mgr": api_key_mgr,
            "data_export": data_export,
            "sla_monitor": sla_monitor,
            "notification_dispatcher": notification_dispatcher,
            "prom_exporter": prom_exporter,
            "grafana_dashboard": grafana_dashboard,
            "request_tracer": request_tracer,
            "monitor": monitor,
            "shutdown_mgr": shutdown_mgr,
            "correlation_mgr": correlation_mgr,
            "idempotency_store": idempotency_store,
            "response_compressor": response_compressor,
            "canary_controller": canary_controller,
            "secret_rotation": secret_rotation,
            "request_dedup": request_dedup,
            "snapshot_mgr": snapshot_mgr,
            "otel_exporter": otel_exporter,
            "circuit_dashboard": circuit_dashboard,
            "deploy_checker": deploy_checker,
            "api_migration": api_migration,
            "retry_engine": retry_engine,
            "region_router": region_router,
            "request_ctx_factory": request_ctx_factory,
            "governed_cache": governed_cache,
            "feature_flags": feature_flags,
            "dep_graph": dep_graph,
            "backpressure": backpressure,
            "ab_engine": ab_engine,
        },
    )

    return DependencyRegistryBootstrap(platform=platform)
