"""
The CONSTRAINT_MATRIX.md artifact must stay in sync with the live
adapter registry. The matrix is generated by walking every adapter's
``translate_to_universal`` under a battery of probes and rendering
the observed (constraint_domain, violation_response) tuples. The
generation is deterministic for a fixed registry, so any change to
adapter governance — adding/removing a constraint, changing a
violation_response, adding a new adapter — must regenerate the file.

This test runs the generator and compares the output to the
checked-in artifact. PRs that change adapter governance without
running ``python -m mcoi.tools.audit_constraint_matrix`` fail here.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from tools.audit_constraint_matrix import (
    ADAPTERS,
    artifact_path,
    discover_constraints,
    generate_matrix,
)


def test_artifact_exists():
    p = artifact_path()
    assert p.exists(), (
        f"CONSTRAINT_MATRIX.md missing at {p}. Generate with "
        "`python -m mcoi.tools.audit_constraint_matrix`."
    )


def test_artifact_is_up_to_date():
    """The on-disk matrix must match what the tool generates right now."""
    p = artifact_path()
    if not p.exists():
        pytest.skip("artifact missing; run audit_constraint_matrix first")
    on_disk = p.read_text(encoding="utf-8")
    fresh = generate_matrix()
    if on_disk != fresh:
        # Diff hint without dumping the whole file
        len_on_disk = len(on_disk)
        len_fresh = len(fresh)
        first_diff = next(
            (i for i, (a, b) in enumerate(zip(on_disk, fresh)) if a != b),
            min(len_on_disk, len_fresh),
        )
        pytest.fail(
            f"CONSTRAINT_MATRIX.md is stale.\n"
            f"  on-disk: {len_on_disk} chars\n"
            f"  fresh:   {len_fresh} chars\n"
            f"  first divergence at offset {first_diff}\n"
            f"Regenerate with: "
            f"`python -m mcoi.tools.audit_constraint_matrix`"
        )


def test_every_registered_adapter_appears_in_artifact():
    """Defensive: even if the tool's rendering changes, every adapter
    name must be present somewhere in the artifact. Catches the case
    where the rendering loop accidentally skips an adapter."""
    p = artifact_path()
    if not p.exists():
        pytest.skip("artifact missing; run audit_constraint_matrix first")
    body = p.read_text(encoding="utf-8")
    for adapter in ADAPTERS:
        assert f"### {adapter.name}" in body, (
            f"Adapter {adapter.name!r} missing from CONSTRAINT_MATRIX.md"
        )


def test_every_adapter_emits_at_least_one_correctness_block():
    """The acceptance-criteria contract: every adapter must emit at
    least one ``<vertical>_correctness`` constraint with
    ``violation_response = block`` when given acceptance_criteria.
    This is the structural universality claim, enforced live."""
    for adapter in ADAPTERS:
        constraints = discover_constraints(adapter)
        correctness_blocks = [
            (d, r) for d, r in constraints
            if d.endswith("_correctness") and r == "block"
        ]
        assert correctness_blocks, (
            f"{adapter.name} did not emit any "
            f"`<vertical>_correctness` constraint with `block` response"
        )


def test_every_violation_response_is_canonical():
    """Every constraint emitted across every adapter must use one of
    the three canonical violation responses. A typo or new value
    surfaces here before it can ship."""
    canonical = {"block", "escalate", "warn"}
    for adapter in ADAPTERS:
        constraints = discover_constraints(adapter)
        for domain, response in constraints:
            assert response in canonical, (
                f"{adapter.name} emitted constraint with "
                f"non-canonical violation_response: "
                f"{domain!r} → {response!r} (allowed: {canonical})"
            )
