"""
Purpose: verify golden output snapshots for the domain adapters.
Governance scope: adapter output drift detection and review evidence.
Dependencies: pytest, adapter registry, and export_adapter_snapshots.
Invariants: each live adapter output matches the committed snapshot.

The cross-adapter invariants pin *structure*; the constraint matrix
pins the *constraint vocabulary*. This file pins the *exact output
values* for each adapter's canonical minimal request, catching
behavioral drift that the structural tests pass over silently:

  - a changed purpose verb (e.g. "issue_funds" -> "execute_transfer")
  - a reordered or renamed authority / observer
  - a flipped violation_response on a single constraint
  - a changed boundary permeability or inside_predicate template
  - an added / removed / reordered protocol step
  - a changed governance_status or risk flag

The golden file is committed at
``tests/golden/domain_adapter_snapshots.json`` and generated by
``tools/export_adapter_snapshots.py``. When an adapter's behavior
changes *deliberately*, regenerate the golden and the diff in the PR
makes the behavior change reviewable. When it changes *accidentally*,
this test fails.

The non-deterministic ``audit_trail_id`` (a fresh UUID per run) is
excluded from the snapshot, so these tests are stable across runs.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from tools.export_adapter_snapshots import (
    artifact_path,
    snapshot_for_adapter,
)
from mcoi_runtime.domain_adapters._registry import ADAPTERS


def _load_golden() -> dict:
    p = artifact_path()
    if not p.exists():
        pytest.skip(
            f"golden snapshot file missing at {p}; generate with "
            "`python -m mcoi.tools.export_adapter_snapshots`"
        )
    return json.loads(p.read_text(encoding="utf-8"))


_GOLDEN = _load_golden()


def test_golden_covers_every_registered_adapter():
    golden_adapters = set(_GOLDEN.get("adapters", {}).keys())
    registry_adapters = {entry.name for entry in ADAPTERS}
    assert golden_adapters == registry_adapters, (
        f"golden / registry mismatch - missing from golden: "
        f"{registry_adapters - golden_adapters}; extra in golden: "
        f"{golden_adapters - registry_adapters}. Regenerate with "
        f"`python -m mcoi.tools.export_adapter_snapshots`."
    )


@pytest.mark.parametrize("entry", ADAPTERS, ids=lambda e: e.name)
def test_adapter_output_matches_golden(entry):
    """The live output for each adapter's canonical request must
    match the committed golden snapshot exactly."""
    golden = _GOLDEN["adapters"].get(entry.name)
    assert golden is not None, (
        f"no golden snapshot for {entry.name}; regenerate."
    )
    live = snapshot_for_adapter(entry)
    assert live == golden, (
        f"{entry.name} output drifted from golden snapshot.\n"
        f"If this change is intentional, regenerate with "
        f"`python -m mcoi.tools.export_adapter_snapshots` and review "
        f"the diff in your PR.\n"
        f"Live purpose: {live['translate']['purpose_statement']!r}\n"
        f"Golden purpose: {golden['translate']['purpose_statement']!r}"
    )


# ---- granular drift checks (clearer failure messages) ----


@pytest.mark.parametrize("entry", ADAPTERS, ids=lambda e: e.name)
def test_purpose_statement_matches_golden(entry):
    live = snapshot_for_adapter(entry)["translate"]["purpose_statement"]
    golden = _GOLDEN["adapters"][entry.name]["translate"]["purpose_statement"]
    assert live == golden, (
        f"{entry.name} purpose_statement changed: "
        f"{golden!r} -> {live!r}"
    )


@pytest.mark.parametrize("entry", ADAPTERS, ids=lambda e: e.name)
def test_constraint_responses_match_golden(entry):
    """The (domain, violation_response) pairs must match golden; the
    most governance-critical drift to catch."""
    live = {
        (c["domain"], c["violation_response"])
        for c in snapshot_for_adapter(entry)["translate"]["constraint_set"]
    }
    golden = {
        (c["domain"], c["violation_response"])
        for c in _GOLDEN["adapters"][entry.name]["translate"]["constraint_set"]
    }
    assert live == golden, (
        f"{entry.name} constraint responses drifted.\n"
        f"  added:   {live - golden}\n"
        f"  removed: {golden - live}"
    )


@pytest.mark.parametrize("entry", ADAPTERS, ids=lambda e: e.name)
def test_governance_status_matches_golden(entry):
    live = snapshot_for_adapter(entry)["run"]["governance_status"]
    golden = _GOLDEN["adapters"][entry.name]["run"]["governance_status"]
    assert live == golden, (
        f"{entry.name} governance_status changed: {golden!r} -> {live!r}"
    )


# ---- staleness ----


def test_golden_file_is_up_to_date():
    """The committed golden must equal what the tool generates now.
    Catches the case where an adapter changed but the golden wasn't
    regenerated."""
    from tools.export_adapter_snapshots import render

    p = artifact_path()
    if not p.exists():
        pytest.skip("golden missing; generate first")
    on_disk = p.read_text(encoding="utf-8")
    fresh = render()
    assert on_disk == fresh, (
        "domain_adapter_snapshots.json is stale relative to the tool. "
        "Regenerate with `python -m mcoi.tools.export_adapter_snapshots`."
    )
