#!/usr/bin/env python3
"""Produce browser sandbox evidence from the governed sandbox runner.

Purpose: emit a concrete sandbox-runner receipt for browser live receipt
production.
Governance scope: [OCE, RAG, CDCV, CQTE, UWMA, PRS]
Dependencies: gateway.sandbox_runner.
Invariants:
  - Evidence is generated by DockerRootlessSandboxRunner.
  - Browser sandbox evidence is Linux/rootless-Docker bounded.
  - Failed sandbox probes remain explicit blockers.
  - Secret values are not serialized.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Callable

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
MCOI_ROOT = REPO_ROOT / "mcoi"
if str(MCOI_ROOT) not in sys.path:
    sys.path.insert(0, str(MCOI_ROOT))

from gateway.sandbox_runner import (  # noqa: E402
    DockerRootlessSandboxRunner,
    Runner,
    SandboxCommandRequest,
)

DEFAULT_OUTPUT = REPO_ROOT / ".change_assurance" / "browser_sandbox_evidence.json"
DEFAULT_REQUEST_ID = "browser-sandbox-evidence"
DEFAULT_TENANT_ID = "tenant-adapter-evidence"
DEFAULT_CAPABILITY_ID = "browser.extract_text"
DEFAULT_PROBE_ARGV = ("python", "--version")


@dataclass(frozen=True, slots=True)
class BrowserSandboxEvidenceResult:
    """Result of one browser sandbox evidence production run."""

    evidence_id: str
    status: str
    output_path: str
    receipt_id: str
    verification_status: str
    blockers: tuple[str, ...]

    @property
    def passed(self) -> bool:
        """Return whether the evidence satisfies browser sandbox admission."""
        return self.status == "passed" and not self.blockers

    def as_dict(self) -> dict[str, Any]:
        """Return a deterministic JSON-ready summary."""
        return {
            "evidence_id": self.evidence_id,
            "status": self.status,
            "output_path": self.output_path,
            "receipt_id": self.receipt_id,
            "verification_status": self.verification_status,
            "blockers": list(self.blockers),
        }


def produce_browser_sandbox_evidence(
    *,
    output_path: Path = DEFAULT_OUTPUT,
    workspace_root: Path = REPO_ROOT,
    request_id: str = DEFAULT_REQUEST_ID,
    tenant_id: str = DEFAULT_TENANT_ID,
    capability_id: str = DEFAULT_CAPABILITY_ID,
    argv: tuple[str, ...] = DEFAULT_PROBE_ARGV,
    cwd: str = "/workspace",
    runner: Runner | None = None,
    platform_system: Callable[[], str] | None = None,
    clock: Callable[[], str] | None = None,
) -> BrowserSandboxEvidenceResult:
    """Produce and write one browser sandbox evidence receipt."""
    resolved_runner = DockerRootlessSandboxRunner(
        host_workspace_root=str(workspace_root),
        runner=runner if runner is not None else subprocess.run,
        platform_system=platform_system or platform.system,
    )
    request = SandboxCommandRequest(
        request_id=request_id,
        tenant_id=tenant_id,
        capability_id=capability_id,
        argv=argv,
        cwd=cwd,
    )
    command_result = resolved_runner.execute(request)
    receipt_payload = asdict(command_result.receipt)
    blockers = _blockers_for(command_result.status, receipt_payload, command_result.stderr)
    status = "passed" if not blockers else "failed"
    evidence_id = _evidence_id(receipt_payload)
    payload = {
        "evidence_id": evidence_id,
        "status": status,
        "checked_at": (clock or _validation_clock)(),
        "workspace_root_hash": _sha256_text(str(Path(workspace_root).resolve(strict=False))),
        "sandbox_profile": {
            "sandbox_id": resolved_runner.profile.sandbox_id,
            "image": resolved_runner.profile.image,
            "network": resolved_runner.profile.network,
            "read_only_rootfs": resolved_runner.profile.read_only_rootfs,
            "workspace_mount": resolved_runner.profile.workspace_mount,
            "timeout_seconds": resolved_runner.profile.timeout_seconds,
            "kill_process_tree": resolved_runner.profile.kill_process_tree,
        },
        "probe": {
            "request_id": request.request_id,
            "tenant_id": request.tenant_id,
            "capability_id": request.capability_id,
            "argv": list(request.argv),
            "cwd": request.cwd,
            "environment_keys": [],
        },
        "receipt": receipt_payload,
        "blockers": list(blockers),
    }
    _write_json(output_path, payload)
    return BrowserSandboxEvidenceResult(
        evidence_id=evidence_id,
        status=status,
        output_path=str(output_path),
        receipt_id=str(receipt_payload["receipt_id"]),
        verification_status=str(receipt_payload["verification_status"]),
        blockers=blockers,
    )


def _blockers_for(status: str, receipt: dict[str, Any], stderr: str) -> tuple[str, ...]:
    blockers: list[str] = []
    if status != "succeeded":
        blockers.append(f"browser_sandbox_probe_{status}")
    if receipt.get("verification_status") != "passed":
        blockers.append(f"browser_sandbox_verification_{receipt.get('verification_status', 'unknown')}")
    if receipt.get("forbidden_effects_observed") is True:
        blockers.append("browser_sandbox_forbidden_effects_observed")
    if stderr == "sandbox runner is linux-only":
        blockers.append("browser_sandbox_runner_linux_only")
    if not str(receipt.get("capability_id", "")).startswith("browser."):
        blockers.append("browser_sandbox_capability_not_browser")
    return tuple(dict.fromkeys(blockers))


def _evidence_id(receipt_payload: dict[str, Any]) -> str:
    digest = hashlib.sha256(
        json.dumps(receipt_payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()
    return f"browser-sandbox-evidence-{digest[:16]}"


def _sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8", errors="replace")).hexdigest()


def _write_json(path: Path, payload: dict[str, Any]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def _validation_clock() -> str:
    return "2026-05-01T12:00:00+00:00"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse browser sandbox evidence producer arguments."""
    parser = argparse.ArgumentParser(description="Produce governed browser sandbox evidence.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--workspace-root", default=str(REPO_ROOT))
    parser.add_argument("--request-id", default=DEFAULT_REQUEST_ID)
    parser.add_argument("--tenant-id", default=DEFAULT_TENANT_ID)
    parser.add_argument("--capability-id", default=DEFAULT_CAPABILITY_ID)
    parser.add_argument("--cwd", default="/workspace")
    parser.add_argument("--argv", nargs="+", default=list(DEFAULT_PROBE_ARGV))
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--strict", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Run the CLI."""
    args = parse_args(argv)
    result = produce_browser_sandbox_evidence(
        output_path=Path(args.output),
        workspace_root=Path(args.workspace_root),
        request_id=args.request_id,
        tenant_id=args.tenant_id,
        capability_id=args.capability_id,
        argv=tuple(str(item) for item in args.argv),
        cwd=args.cwd,
    )
    if args.json:
        print(json.dumps(result.as_dict(), indent=2, sort_keys=True))
    elif result.passed:
        print(f"BROWSER SANDBOX EVIDENCE PASSED receipt_id={result.receipt_id}")
    else:
        print(f"BROWSER SANDBOX EVIDENCE FAILED blockers={list(result.blockers)}")
    return 0 if result.passed or not args.strict else 2


if __name__ == "__main__":
    raise SystemExit(main())
