#!/usr/bin/env python3
"""Validate the repository Foundation Mode posture.

Purpose: keep current public-copy and operator guidance aligned with the
solo-founder Foundation Mode boundary.
Governance scope: Foundation Mode, public copy, pilot/access claims, deployment
restraint, and current posture docs.
Dependencies: repository-local Markdown, HTML, and Python guidance files.
Invariants:
  - Current guidance remains local-proof-first.
  - Customer access, pilot access, beta invitation, waitlist, endpoint-readiness,
    and deployment claims remain blocked unless explicitly promoted by evidence.
  - Historical evidence files are not rewritten or treated as current guidance.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import sys


REPO_ROOT = Path(__file__).resolve().parents[1]

REQUIRED_PHRASES_BY_FILE = {
    "AGENTS.md": (
        "Assume `Foundation Mode` unless the user or a signed status witness explicitly",
        "before deployment, company formation, customer access",
        "Do not push toward public deployment, paid launch, LLC formation",
    ),
    "README.md": (
        "## Current Operating Posture: Foundation Mode",
        "private, local-first",
        "See [`docs/FOUNDATION_MODE.md`](docs/FOUNDATION_MODE.md)",
        "[`docs/FOUNDATION_PREREQUISITES.md`](docs/FOUNDATION_PREREQUISITES.md)",
        "[`docs/FOUNDATION_OPERATOR_READINESS_BOUNDARY.md`](docs/FOUNDATION_OPERATOR_READINESS_BOUNDARY.md)",
        "[`docs/FOUNDATION_LEARNING_PATH_BOUNDARY.md`](docs/FOUNDATION_LEARNING_PATH_BOUNDARY.md)",
        "[`docs/FOUNDATION_COMMUNITY_NETWORK_BOUNDARY.md`](docs/FOUNDATION_COMMUNITY_NETWORK_BOUNDARY.md)",
        "[`docs/FOUNDATION_ARCHITECTURE_MAP_BOUNDARY.md`](docs/FOUNDATION_ARCHITECTURE_MAP_BOUNDARY.md)",
        "[`docs/FOUNDATION_SYSTEM_BOUNDARY_INVENTORY_BOUNDARY.md`](docs/FOUNDATION_SYSTEM_BOUNDARY_INVENTORY_BOUNDARY.md)",
        "[`docs/FOUNDATION_MODULE_INVENTORY_BOUNDARY.md`](docs/FOUNDATION_MODULE_INVENTORY_BOUNDARY.md)",
        "[`docs/FOUNDATION_COMPONENT_CONTRACT_BOUNDARY.md`](docs/FOUNDATION_COMPONENT_CONTRACT_BOUNDARY.md)",
        "[`docs/FOUNDATION_INTERFACE_MAP_BOUNDARY.md`](docs/FOUNDATION_INTERFACE_MAP_BOUNDARY.md)",
        "[`docs/FOUNDATION_DEPENDENCY_GRAPH_BOUNDARY.md`](docs/FOUNDATION_DEPENDENCY_GRAPH_BOUNDARY.md)",
        "[`docs/FOUNDATION_INVARIANT_MAP_BOUNDARY.md`](docs/FOUNDATION_INVARIANT_MAP_BOUNDARY.md)",
        "[`docs/FOUNDATION_HAZARD_MAP_BOUNDARY.md`](docs/FOUNDATION_HAZARD_MAP_BOUNDARY.md)",
        "[`docs/FOUNDATION_PROOF_REFERENCE_BOUNDARY.md`](docs/FOUNDATION_PROOF_REFERENCE_BOUNDARY.md)",
        "[`docs/FOUNDATION_GAP_REGISTER_BOUNDARY.md`](docs/FOUNDATION_GAP_REGISTER_BOUNDARY.md)",
        "[`docs/FOUNDATION_DIFF_REVIEW_BOUNDARY.md`](docs/FOUNDATION_DIFF_REVIEW_BOUNDARY.md)",
        "[`docs/FOUNDATION_CHANGE_HANDOFF_BOUNDARY.md`](docs/FOUNDATION_CHANGE_HANDOFF_BOUNDARY.md)",
        "[`docs/FOUNDATION_LOCAL_WORKSTATION_BOUNDARY.md`](docs/FOUNDATION_LOCAL_WORKSTATION_BOUNDARY.md)",
        "[`docs/FOUNDATION_DOCUMENTATION_BOUNDARY.md`](docs/FOUNDATION_DOCUMENTATION_BOUNDARY.md)",
        "[`docs/FOUNDATION_PLAIN_LANGUAGE_STATUS_BOUNDARY.md`](docs/FOUNDATION_PLAIN_LANGUAGE_STATUS_BOUNDARY.md)",
        "[`docs/FOUNDATION_CLAIM_BOUNDARY.md`](docs/FOUNDATION_CLAIM_BOUNDARY.md)",
        "[`docs/FOUNDATION_WEBSITE_POSTURE_BOUNDARY.md`](docs/FOUNDATION_WEBSITE_POSTURE_BOUNDARY.md)",
        "[`docs/FOUNDATION_RESEARCH_NOTEBOOK_BOUNDARY.md`](docs/FOUNDATION_RESEARCH_NOTEBOOK_BOUNDARY.md)",
        "[`docs/FOUNDATION_EVIDENCE_LEDGER_BOUNDARY.md`](docs/FOUNDATION_EVIDENCE_LEDGER_BOUNDARY.md)",
        "[`docs/FOUNDATION_DECISION_JOURNAL_BOUNDARY.md`](docs/FOUNDATION_DECISION_JOURNAL_BOUNDARY.md)",
        "[`docs/FOUNDATION_NEXT_ACTION_BOUNDARY.md`](docs/FOUNDATION_NEXT_ACTION_BOUNDARY.md)",
        "[`docs/FOUNDATION_TEST_EVIDENCE_BOUNDARY.md`](docs/FOUNDATION_TEST_EVIDENCE_BOUNDARY.md)",
        "[`docs/FOUNDATION_SOURCE_CONTROL_BOUNDARY.md`](docs/FOUNDATION_SOURCE_CONTROL_BOUNDARY.md)",
        "[`docs/FOUNDATION_LOCAL_PROOF_THREAD.md`](docs/FOUNDATION_LOCAL_PROOF_THREAD.md)",
        "[`docs/FOUNDATION_SECRETS_CREDENTIALS_BOUNDARY.md`](docs/FOUNDATION_SECRETS_CREDENTIALS_BOUNDARY.md)",
        "[`docs/FOUNDATION_SECURITY_BASELINE_BOUNDARY.md`](docs/FOUNDATION_SECURITY_BASELINE_BOUNDARY.md)",
        "[`docs/FOUNDATION_COST_BUDGET_BOUNDARY.md`](docs/FOUNDATION_COST_BUDGET_BOUNDARY.md)",
        "[`docs/FOUNDATION_PAYMENT_PROVIDER_BOUNDARY.md`](docs/FOUNDATION_PAYMENT_PROVIDER_BOUNDARY.md)",
        "[`docs/FOUNDATION_RUNTIME_ENVIRONMENT_BOUNDARY.md`](docs/FOUNDATION_RUNTIME_ENVIRONMENT_BOUNDARY.md)",
        "[`docs/FOUNDATION_BACKUP_EXPORT_BOUNDARY.md`](docs/FOUNDATION_BACKUP_EXPORT_BOUNDARY.md)",
        "[`docs/FOUNDATION_DEPLOYMENT_DEFERRAL_BOUNDARY.md`](docs/FOUNDATION_DEPLOYMENT_DEFERRAL_BOUNDARY.md)",
        "[`docs/FOUNDATION_EXTERNAL_INFRASTRUCTURE_BOUNDARY.md`](docs/FOUNDATION_EXTERNAL_INFRASTRUCTURE_BOUNDARY.md)",
        "[`docs/FOUNDATION_PILOT_DEFERRAL_BOUNDARY.md`](docs/FOUNDATION_PILOT_DEFERRAL_BOUNDARY.md)",
        "[`docs/FOUNDATION_PRODUCT_SCOPE_BOUNDARY.md`](docs/FOUNDATION_PRODUCT_SCOPE_BOUNDARY.md)",
        "[`docs/FOUNDATION_SUPPORT_READINESS_BOUNDARY.md`](docs/FOUNDATION_SUPPORT_READINESS_BOUNDARY.md)",
        "[`docs/FOUNDATION_INTAKE_ONBOARDING_BOUNDARY.md`](docs/FOUNDATION_INTAKE_ONBOARDING_BOUNDARY.md)",
        "[`docs/FOUNDATION_PRIVACY_DATA_BOUNDARY.md`](docs/FOUNDATION_PRIVACY_DATA_BOUNDARY.md)",
        "[`docs/FOUNDATION_CUSTOMER_ACCESS_BOUNDARY.md`](docs/FOUNDATION_CUSTOMER_ACCESS_BOUNDARY.md)",
        "[`docs/FOUNDATION_PRIVATE_RECOVERY_BOUNDARY.md`](docs/FOUNDATION_PRIVATE_RECOVERY_BOUNDARY.md)",
        "[`docs/FOUNDATION_DOMAIN_EMAIL_BOUNDARY.md`](docs/FOUNDATION_DOMAIN_EMAIL_BOUNDARY.md)",
        "[`docs/FOUNDATION_LEGAL_BUSINESS_BOUNDARY.md`](docs/FOUNDATION_LEGAL_BUSINESS_BOUNDARY.md)",
        "[`docs/FOUNDATION_FUNDING_TEAM_BOUNDARY.md`](docs/FOUNDATION_FUNDING_TEAM_BOUNDARY.md)",
    ),
    "docs/FOUNDATION_MODE.md": (
        "Foundation Mode means the project is being prepared carefully",
        "before deployment, company formation, customer access, or paid infrastructure",
        "For the step-by-step prerequisite ledger",
        "[Foundation Prerequisites](FOUNDATION_PREREQUISITES.md)",
        "[Foundation Operator Readiness Boundary](FOUNDATION_OPERATOR_READINESS_BOUNDARY.md)",
        "[Foundation Learning Path Boundary](FOUNDATION_LEARNING_PATH_BOUNDARY.md)",
        "[Foundation Community Network Boundary](FOUNDATION_COMMUNITY_NETWORK_BOUNDARY.md)",
        "[Foundation Architecture Map Boundary](FOUNDATION_ARCHITECTURE_MAP_BOUNDARY.md)",
        "[Foundation System Boundary Inventory Boundary](FOUNDATION_SYSTEM_BOUNDARY_INVENTORY_BOUNDARY.md)",
        "[Foundation Module Inventory Boundary](FOUNDATION_MODULE_INVENTORY_BOUNDARY.md)",
        "[Foundation Component Contract Boundary](FOUNDATION_COMPONENT_CONTRACT_BOUNDARY.md)",
        "[Foundation Interface Map Boundary](FOUNDATION_INTERFACE_MAP_BOUNDARY.md)",
        "[Foundation Dependency Graph Boundary](FOUNDATION_DEPENDENCY_GRAPH_BOUNDARY.md)",
        "[Foundation Invariant Map Boundary](FOUNDATION_INVARIANT_MAP_BOUNDARY.md)",
        "[Foundation Hazard Map Boundary](FOUNDATION_HAZARD_MAP_BOUNDARY.md)",
        "[Foundation Proof Reference Boundary](FOUNDATION_PROOF_REFERENCE_BOUNDARY.md)",
        "[Foundation Gap Register Boundary](FOUNDATION_GAP_REGISTER_BOUNDARY.md)",
        "[Foundation Diff Review Boundary](FOUNDATION_DIFF_REVIEW_BOUNDARY.md)",
        "[Foundation Change Handoff Boundary](FOUNDATION_CHANGE_HANDOFF_BOUNDARY.md)",
        "[Foundation Local Workstation Boundary](FOUNDATION_LOCAL_WORKSTATION_BOUNDARY.md)",
        "[Foundation Documentation Boundary](FOUNDATION_DOCUMENTATION_BOUNDARY.md)",
        "[Foundation Plain-Language Status Boundary](FOUNDATION_PLAIN_LANGUAGE_STATUS_BOUNDARY.md)",
        "[Foundation Claim Boundary](FOUNDATION_CLAIM_BOUNDARY.md)",
        "[Foundation Website Posture Boundary](FOUNDATION_WEBSITE_POSTURE_BOUNDARY.md)",
        "[Foundation Research Notebook Boundary](FOUNDATION_RESEARCH_NOTEBOOK_BOUNDARY.md)",
        "[Foundation Evidence Ledger Boundary](FOUNDATION_EVIDENCE_LEDGER_BOUNDARY.md)",
        "[Foundation Decision Journal Boundary](FOUNDATION_DECISION_JOURNAL_BOUNDARY.md)",
        "[Foundation Next Action Boundary](FOUNDATION_NEXT_ACTION_BOUNDARY.md)",
        "[Foundation Test Evidence Boundary](FOUNDATION_TEST_EVIDENCE_BOUNDARY.md)",
        "[Foundation Source Control Boundary](FOUNDATION_SOURCE_CONTROL_BOUNDARY.md)",
        "[Foundation Secrets Credentials Boundary](FOUNDATION_SECRETS_CREDENTIALS_BOUNDARY.md)",
        "[Foundation Security Baseline Boundary](FOUNDATION_SECURITY_BASELINE_BOUNDARY.md)",
        "[Foundation Cost Budget Boundary](FOUNDATION_COST_BUDGET_BOUNDARY.md)",
        "[Foundation Payment Provider Boundary](FOUNDATION_PAYMENT_PROVIDER_BOUNDARY.md)",
        "[Foundation Runtime Environment Boundary](FOUNDATION_RUNTIME_ENVIRONMENT_BOUNDARY.md)",
        "[Foundation Backup Export Boundary](FOUNDATION_BACKUP_EXPORT_BOUNDARY.md)",
        "[Foundation Deployment Deferral Boundary](FOUNDATION_DEPLOYMENT_DEFERRAL_BOUNDARY.md)",
        "[Foundation External Infrastructure Boundary](FOUNDATION_EXTERNAL_INFRASTRUCTURE_BOUNDARY.md)",
        "[Foundation Pilot Deferral Boundary](FOUNDATION_PILOT_DEFERRAL_BOUNDARY.md)",
        "[Foundation Private Recovery Boundary](FOUNDATION_PRIVATE_RECOVERY_BOUNDARY.md)",
        "[Foundation Domain Email Boundary](FOUNDATION_DOMAIN_EMAIL_BOUNDARY.md)",
        "[Foundation Product Scope Boundary](FOUNDATION_PRODUCT_SCOPE_BOUNDARY.md)",
        "[Foundation Support Readiness Boundary](FOUNDATION_SUPPORT_READINESS_BOUNDARY.md)",
        "[Foundation Intake Onboarding Boundary](FOUNDATION_INTAKE_ONBOARDING_BOUNDARY.md)",
        "[Foundation Privacy Data Boundary](FOUNDATION_PRIVACY_DATA_BOUNDARY.md)",
        "[Foundation Customer Access Boundary](FOUNDATION_CUSTOMER_ACCESS_BOUNDARY.md)",
        "[Foundation Legal Business Boundary](FOUNDATION_LEGAL_BUSINESS_BOUNDARY.md)",
        "Do not push toward deployment, public launch, customers, LLC formation",
    ),
    "docs/FOUNDATION_PREREQUISITES.md": (
        "this is the checklist for preparing the foundation before",
        "Atomic Prerequisite Ledger",
        "[Foundation Operator Readiness Boundary](FOUNDATION_OPERATOR_READINESS_BOUNDARY.md)",
        "[Foundation Learning Path Boundary](FOUNDATION_LEARNING_PATH_BOUNDARY.md)",
        "[Foundation Community Network Boundary](FOUNDATION_COMMUNITY_NETWORK_BOUNDARY.md)",
        "[Foundation Architecture Map Boundary](FOUNDATION_ARCHITECTURE_MAP_BOUNDARY.md)",
        "[Foundation System Boundary Inventory Boundary](FOUNDATION_SYSTEM_BOUNDARY_INVENTORY_BOUNDARY.md)",
        "[Foundation Module Inventory Boundary](FOUNDATION_MODULE_INVENTORY_BOUNDARY.md)",
        "[Foundation Component Contract Boundary](FOUNDATION_COMPONENT_CONTRACT_BOUNDARY.md)",
        "[Foundation Interface Map Boundary](FOUNDATION_INTERFACE_MAP_BOUNDARY.md)",
        "[Foundation Dependency Graph Boundary](FOUNDATION_DEPENDENCY_GRAPH_BOUNDARY.md)",
        "[Foundation Invariant Map Boundary](FOUNDATION_INVARIANT_MAP_BOUNDARY.md)",
        "[Foundation Hazard Map Boundary](FOUNDATION_HAZARD_MAP_BOUNDARY.md)",
        "[Foundation Proof Reference Boundary](FOUNDATION_PROOF_REFERENCE_BOUNDARY.md)",
        "[Foundation Gap Register Boundary](FOUNDATION_GAP_REGISTER_BOUNDARY.md)",
        "[Foundation Diff Review Boundary](FOUNDATION_DIFF_REVIEW_BOUNDARY.md)",
        "[Foundation Change Handoff Boundary](FOUNDATION_CHANGE_HANDOFF_BOUNDARY.md)",
        "[Foundation Local Workstation Boundary](FOUNDATION_LOCAL_WORKSTATION_BOUNDARY.md)",
        "[Foundation Documentation Boundary](FOUNDATION_DOCUMENTATION_BOUNDARY.md)",
        "[Foundation Plain-Language Status Boundary](FOUNDATION_PLAIN_LANGUAGE_STATUS_BOUNDARY.md)",
        "[Foundation Claim Boundary](FOUNDATION_CLAIM_BOUNDARY.md)",
        "[Foundation Website Posture Boundary](FOUNDATION_WEBSITE_POSTURE_BOUNDARY.md)",
        "[Foundation Research Notebook Boundary](FOUNDATION_RESEARCH_NOTEBOOK_BOUNDARY.md)",
        "[Foundation Evidence Ledger Boundary](FOUNDATION_EVIDENCE_LEDGER_BOUNDARY.md)",
        "[Foundation Decision Journal Boundary](FOUNDATION_DECISION_JOURNAL_BOUNDARY.md)",
        "[Foundation Next Action Boundary](FOUNDATION_NEXT_ACTION_BOUNDARY.md)",
        "[Foundation Test Evidence Boundary](FOUNDATION_TEST_EVIDENCE_BOUNDARY.md)",
        "[Foundation Source Control Boundary](FOUNDATION_SOURCE_CONTROL_BOUNDARY.md)",
        "[Foundation Local Proof Thread](FOUNDATION_LOCAL_PROOF_THREAD.md)",
        "[Foundation Private Recovery Boundary](FOUNDATION_PRIVATE_RECOVERY_BOUNDARY.md)",
        "[Foundation Secrets Credentials Boundary](FOUNDATION_SECRETS_CREDENTIALS_BOUNDARY.md)",
        "[Foundation Security Baseline Boundary](FOUNDATION_SECURITY_BASELINE_BOUNDARY.md)",
        "[Foundation Cost Budget Boundary](FOUNDATION_COST_BUDGET_BOUNDARY.md)",
        "[Foundation Payment Provider Boundary](FOUNDATION_PAYMENT_PROVIDER_BOUNDARY.md)",
        "[Foundation Runtime Environment Boundary](FOUNDATION_RUNTIME_ENVIRONMENT_BOUNDARY.md)",
        "[Foundation Backup Export Boundary](FOUNDATION_BACKUP_EXPORT_BOUNDARY.md)",
        "[Foundation Deployment Deferral Boundary](FOUNDATION_DEPLOYMENT_DEFERRAL_BOUNDARY.md)",
        "[Foundation External Infrastructure Boundary](FOUNDATION_EXTERNAL_INFRASTRUCTURE_BOUNDARY.md)",
        "[Foundation Pilot Deferral Boundary](FOUNDATION_PILOT_DEFERRAL_BOUNDARY.md)",
        "[Foundation Domain Email Boundary](FOUNDATION_DOMAIN_EMAIL_BOUNDARY.md)",
        "[Foundation Product Scope Boundary](FOUNDATION_PRODUCT_SCOPE_BOUNDARY.md)",
        "[Foundation Support Readiness Boundary](FOUNDATION_SUPPORT_READINESS_BOUNDARY.md)",
        "[Foundation Intake Onboarding Boundary](FOUNDATION_INTAKE_ONBOARDING_BOUNDARY.md)",
        "[Foundation Privacy Data Boundary](FOUNDATION_PRIVACY_DATA_BOUNDARY.md)",
        "[Foundation Customer Access Boundary](FOUNDATION_CUSTOMER_ACCESS_BOUNDARY.md)",
        "[Foundation Legal Business Boundary](FOUNDATION_LEGAL_BUSINESS_BOUNDARY.md)",
        "[Foundation Funding Team Boundary](FOUNDATION_FUNDING_TEAM_BOUNDARY.md)",
        "Do not claim legal clearance, patent protection, or company readiness",
        "No customer access or deployment claim",
        "When a future request says \"continue,\" use this order",
    ),
    "docs/FOUNDATION_LOCAL_PROOF_THREAD.md": (
        "the first proof thread is one harmless local workflow",
        "Descriptor: [`../examples/foundation_local_proof_thread.workflow.json`]",
        "python scripts/run_foundation_local_proof_thread.py",
        "Rule: No customer access or deployment claim.",
        "The default receipt is local evidence only",
    ),
    "docs/FOUNDATION_SOURCE_CONTROL_BOUNDARY.md": (
        "Foundation Source Control Boundary",
        "Boundary packet: [`../examples/foundation_source_control_boundary.awaiting_commit.json`]",
        "Rule: Commit readiness is prepared locally, but commit execution requires an",
        "No staging, commit, push, pull request, release, deployment, customer access, or",
        "source_control_boundary_state=AwaitingEvidence",
        "commit_allowed=false",
        "pull_request_allowed=false",
    ),
    "docs/FOUNDATION_OPERATOR_READINESS_BOUNDARY.md": (
        "Foundation Operator Readiness Boundary",
        "Witness packet: [`../examples/foundation_operator_readiness_witness.awaiting_evidence.json`]",
        "Rule: Operator-readiness preparation is a local planning boundary, not",
        "No solo-operator capacity verification, schedule-readiness claim,",
        "operator_readiness_boundary_state=AwaitingEvidence",
        "operator_capacity_verified=false",
        "schedule_readiness_claimed=false",
        "team_readiness_claimed=false",
        "deployment_allowed=false",
    ),
    "docs/FOUNDATION_LEARNING_PATH_BOUNDARY.md": (
        "Foundation Learning Path Boundary",
        "Witness packet: [`../examples/foundation_learning_path_witness.awaiting_evidence.json`]",
        "Rule: Learning-path preparation is a local planning boundary, not a skill,",
        "No skill-readiness claim, training-completion claim, certification claim,",
        "learning_path_boundary_state=AwaitingEvidence",
        "skill_readiness_claimed=false",
        "training_completion_claimed=false",
        "certification_claimed=false",
        "paid_course_allowed=false",
        "mentor_assignment_allowed=false",
        "external_account_use_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_learning_path_boundary.py",
    ),
    "docs/FOUNDATION_ARCHITECTURE_MAP_BOUNDARY.md": (
        "Foundation Architecture Map Boundary",
        "Witness packet: [`../examples/foundation_architecture_map_witness.awaiting_evidence.json`]",
        "Rule: Architecture-map preparation is a local planning boundary, not an architecture-completion",
        "No architecture-completeness claim, module-inventory completeness claim,",
        "architecture_map_boundary_state=AwaitingEvidence",
        "architecture_complete_claimed=false",
        "module_inventory_complete_claimed=false",
        "interface_contract_ready_claimed=false",
        "integration_readiness_claimed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_architecture_map_boundary.py",
    ),
    "docs/FOUNDATION_SYSTEM_BOUNDARY_INVENTORY_BOUNDARY.md": (
        "Foundation System Boundary Inventory Boundary",
        "Witness packet: [`../examples/foundation_system_boundary_inventory_witness.awaiting_evidence.json`]",
        "Rule: System-boundary inventory preparation is a local planning boundary, not a system-boundary-completion",
        "No system-boundary inventory completeness, ownership-boundary closure, trust-boundary closure,",
        "system_boundary_inventory_boundary_state=AwaitingEvidence",
        "system_boundary_inventory_complete_claimed=false",
        "ownership_boundary_closed_claimed=false",
        "trust_boundary_closed_claimed=false",
        "tenant_boundary_ready_claimed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_system_boundary_inventory_boundary.py",
    ),
    "docs/FOUNDATION_MODULE_INVENTORY_BOUNDARY.md": (
        "Foundation Module Inventory Boundary",
        "Witness packet: [`../examples/foundation_module_inventory_witness.awaiting_evidence.json`]",
        "Rule: Module-inventory preparation is a local planning boundary, not a module-inventory-completion",
        "No module inventory completeness, module ownership assignment, module contract",
        "module_inventory_boundary_state=AwaitingEvidence",
        "module_inventory_complete_claimed=false",
        "module_ownership_assigned=false",
        "module_contract_ready_claimed=false",
        "implementation_approval_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_module_inventory_boundary.py",
    ),
    "docs/FOUNDATION_COMPONENT_CONTRACT_BOUNDARY.md": (
        "Foundation Component Contract Boundary",
        "Witness packet: [`../examples/foundation_component_contract_witness.awaiting_evidence.json`]",
        "Rule: Component-contract preparation is a local planning boundary, not a",
        "No component contract readiness, input contract readiness, output contract",
        "component_contract_boundary_state=AwaitingEvidence",
        "component_contract_ready_claimed=false",
        "input_contract_ready_claimed=false",
        "output_contract_ready_claimed=false",
        "owner_approval_assigned=false",
        "test_pass_claimed=false",
        "implementation_approval_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_component_contract_boundary.py",
    ),
    "docs/FOUNDATION_INTERFACE_MAP_BOUNDARY.md": (
        "Foundation Interface Map Boundary",
        "Witness packet: [`../examples/foundation_interface_map_witness.awaiting_evidence.json`]",
        "Rule: Interface-map preparation is a local planning boundary, not an",
        "No interface-map completeness, interface contract readiness, endpoint",
        "interface_map_boundary_state=AwaitingEvidence",
        "interface_map_complete_claimed=false",
        "interface_contract_ready_claimed=false",
        "endpoint_ready_claimed=false",
        "service_binding_claimed=false",
        "integration_ready_claimed=false",
        "implementation_approval_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_interface_map_boundary.py",
    ),
    "docs/FOUNDATION_DEPENDENCY_GRAPH_BOUNDARY.md": (
        "Foundation Dependency Graph Boundary",
        "Witness packet: [`../examples/foundation_dependency_graph_witness.awaiting_evidence.json`]",
        "Rule: Dependency-graph preparation is a local planning boundary, not a",
        "No dependency-graph completeness, dependency contract readiness, import",
        "dependency_graph_boundary_state=AwaitingEvidence",
        "dependency_graph_complete_claimed=false",
        "dependency_contract_ready_claimed=false",
        "import_boundary_ready_claimed=false",
        "package_install_allowed=false",
        "version_lock_ready_claimed=false",
        "service_dependency_bound=false",
        "external_provider_bound=false",
        "implementation_approval_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_dependency_graph_boundary.py",
    ),
    "docs/FOUNDATION_INVARIANT_MAP_BOUNDARY.md": (
        "Foundation Invariant Map Boundary",
        "Witness packet: [`../examples/foundation_invariant_map_witness.awaiting_evidence.json`]",
        "Rule: Invariant-map preparation is a local planning boundary, not an",
        "No invariant-map completeness, invariant proof readiness, invariant",
        "invariant_map_boundary_state=AwaitingEvidence",
        "invariant_map_complete_claimed=false",
        "invariant_proof_ready_claimed=false",
        "invariant_enforcement_ready_claimed=false",
        "invariant_monitor_ready_claimed=false",
        "runtime_invariant_ready_claimed=false",
        "implementation_approval_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_invariant_map_boundary.py",
    ),
    "docs/FOUNDATION_HAZARD_MAP_BOUNDARY.md": (
        "Foundation Hazard Map Boundary",
        "Witness packet: [`../examples/foundation_hazard_map_witness.awaiting_evidence.json`]",
        "Rule: Hazard-map preparation is a local planning boundary, not a",
        "No hazard-map completeness, hazard classification readiness, hazard severity",
        "hazard_map_boundary_state=AwaitingEvidence",
        "hazard_map_complete_claimed=false",
        "hazard_classification_ready_claimed=false",
        "hazard_severity_closed_claimed=false",
        "hazard_mitigation_ready_claimed=false",
        "safety_review_ready_claimed=false",
        "runtime_hazard_ready_claimed=false",
        "implementation_approval_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_hazard_map_boundary.py",
    ),
    "docs/FOUNDATION_PROOF_REFERENCE_BOUNDARY.md": (
        "Foundation Proof Reference Boundary",
        "Witness packet: [`../examples/foundation_proof_reference_witness.awaiting_evidence.json`]",
        "Rule: Proof-reference preparation is a local planning boundary, not a",
        "No proof-reference completeness, proof coverage closure, evidence",
        "proof_reference_boundary_state=AwaitingEvidence",
        "proof_reference_complete_claimed=false",
        "proof_coverage_closed_claimed=false",
        "evidence_promotion_allowed=false",
        "terminal_closure_claimed=false",
        "verification_pass_claimed=false",
        "proof_approval_assigned=false",
        "runtime_proof_ready_claimed=false",
        "implementation_approval_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_proof_reference_boundary.py",
    ),
    "docs/FOUNDATION_GAP_REGISTER_BOUNDARY.md": (
        "Foundation Gap Register Boundary",
        "Witness packet: [`../examples/foundation_gap_register_witness.awaiting_evidence.json`]",
        "Rule: Gap-register preparation is a local planning boundary, not a",
        "No gap-register completeness, gap closure, priority closure, owner",
        "gap_register_boundary_state=AwaitingEvidence",
        "gap_register_complete_claimed=false",
        "gap_closure_claimed=false",
        "gap_priority_closed_claimed=false",
        "gap_owner_assigned=false",
        "remediation_ready_claimed=false",
        "roadmap_commitment_allowed=false",
        "implementation_approval_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_gap_register_boundary.py",
    ),
    "docs/FOUNDATION_DIFF_REVIEW_BOUNDARY.md": (
        "Foundation Diff Review Boundary",
        "Witness packet: [`../examples/foundation_diff_review_witness.awaiting_evidence.json`]",
        "Rule: Diff-review preparation is a local planning boundary, not a",
        "No diff-review completeness, diff scope closure, ownership assignment, staging",
        "diff_review_boundary_state=AwaitingEvidence",
        "diff_review_complete_claimed=false",
        "diff_scope_closed_claimed=false",
        "diff_ownership_assigned=false",
        "staging_allowed=false",
        "commit_allowed=false",
        "push_allowed=false",
        "pull_request_allowed=false",
        "source_control_publication_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_diff_review_boundary.py",
    ),
    "docs/FOUNDATION_CHANGE_HANDOFF_BOUNDARY.md": (
        "Foundation Change Handoff Boundary",
        "Witness packet: [`../examples/foundation_change_handoff_witness.awaiting_evidence.json`]",
        "Rule: Change-handoff preparation is a local planning boundary, not a",
        "No change-handoff completeness, changed-file review completeness, diff scope",
        "change_handoff_boundary_state=AwaitingEvidence",
        "change_handoff_complete_claimed=false",
        "changed_file_review_complete_claimed=false",
        "diff_scope_closed_claimed=false",
        "change_ownership_assigned=false",
        "validation_complete_claimed=false",
        "secret_clearance_claimed=false",
        "staging_allowed=false",
        "commit_allowed=false",
        "push_allowed=false",
        "pull_request_allowed=false",
        "source_control_publication_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_change_handoff_boundary.py",
    ),
    "docs/FOUNDATION_LOCAL_WORKSTATION_BOUNDARY.md": (
        "Foundation Local Workstation Boundary",
        "Witness packet: [`../examples/foundation_local_workstation_witness.awaiting_evidence.json`]",
        "Rule: Local-workstation preparation is a local planning boundary, not",
        "No local workstation verification, Python toolchain verification, Node",
        "local_workstation_boundary_state=AwaitingEvidence",
        "local_workstation_verified=false",
        "python_toolchain_verified=false",
        "dependency_install_allowed=false",
        "deployment_allowed=false",
    ),
    "docs/FOUNDATION_DOCUMENTATION_BOUNDARY.md": (
        "Foundation Documentation Boundary",
        "Witness packet: [`../examples/foundation_documentation_witness.awaiting_evidence.json`]",
        "Rule: Documentation preparation is a local planning boundary, not a readiness certificate.",
        "No documentation completeness claim, canonical-docs claim, public-launch copy",
        "documentation_boundary_state=AwaitingEvidence",
        "documentation_complete_claimed=false",
        "canonical_docs_claimed=false",
        "public_launch_copy_claimed=false",
        "external_publication_allowed=false",
        "deployment_allowed=false",
    ),
    "docs/FOUNDATION_PLAIN_LANGUAGE_STATUS_BOUNDARY.md": (
        "Foundation Plain-Language Status Boundary",
        "Witness packet: [`../examples/foundation_plain_language_status_witness.awaiting_evidence.json`]",
        "Rule: Plain-language status preparation is a local planning boundary, not a",
        "No plain-language completeness, non-technical comprehension proof, product",
        "plain_language_status_boundary_state=AwaitingEvidence",
        "plain_language_complete_claimed=false",
        "nontechnical_comprehension_proven=false",
        "product_readiness_claimed=false",
        "capability_availability_claimed=false",
        "real_task_execution_ready=false",
        "customer_readiness_claimed=false",
        "paid_use_ready_claimed=false",
        "money_movement_ready_claimed=false",
        "canonical_docs_claimed=false",
        "external_publication_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_plain_language_status_boundary.py",
    ),
    "docs/FOUNDATION_CLAIM_BOUNDARY.md": (
        "Foundation Claim Boundary",
        "Witness packet: [`../examples/foundation_claim_boundary_witness.awaiting_evidence.json`]",
        "Rule: Claim-boundary preparation is a local planning boundary, not a claim-promotion certificate.",
        "No production-health claim, endpoint-readiness claim, customer-readiness claim,",
        "claim_boundary_state=AwaitingEvidence",
        "production_health_claimed=false",
        "endpoint_readiness_claimed=false",
        "customer_readiness_claimed=false",
        "external_publication_allowed=false",
        "deployment_allowed=false",
    ),
    "docs/FOUNDATION_WEBSITE_POSTURE_BOUNDARY.md": (
        "Foundation Website Posture Boundary",
        "Witness packet: [`../examples/foundation_website_posture_witness.awaiting_evidence.json`]",
        "Rule: Website-posture preparation is a local planning boundary, not a website publication or access-opening certificate.",
        "No website mutation, external website publication, access invitation, waitlist",
        "website_posture_boundary_state=AwaitingEvidence",
        "website_mutation_allowed=false",
        "access_invitation_allowed=false",
        "waitlist_open=false",
        "external_publication_allowed=false",
        "deployment_allowed=false",
    ),
    "docs/FOUNDATION_RESEARCH_NOTEBOOK_BOUNDARY.md": (
        "Foundation Research Notebook Boundary",
        "Witness packet: [`../examples/foundation_research_notebook_witness.awaiting_evidence.json`]",
        "Rule: Research-notebook preparation is a local planning boundary, not a patent, secrecy, validation, publication, market, or deployment certificate.",
        "No patent protection, trade-secret protection, scientific validation,",
        "research_notebook_boundary_state=AwaitingEvidence",
        "patent_protection_claimed=false",
        "trade_secret_protection_claimed=false",
        "scientific_validation_claimed=false",
        "secret_evidence_claimed=false",
        "deployment_allowed=false",
    ),
    "docs/FOUNDATION_EVIDENCE_LEDGER_BOUNDARY.md": (
        "Foundation Evidence Ledger Boundary",
        "Witness packet: [`../examples/foundation_evidence_ledger_witness.awaiting_evidence.json`]",
        "Rule: Evidence-ledger preparation is a local planning boundary, not a terminal-closure, readiness, legal, patent, customer, publication, paid-launch, secret-evidence, or deployment certificate.",
        "No terminal closure, readiness promotion, legal clearance, patent protection,",
        "evidence_ledger_boundary_state=AwaitingEvidence",
        "evidence_promotion_allowed=false",
        "terminal_closure_claimed=false",
        "readiness_claimed=false",
        "secret_evidence_recorded=false",
        "deployment_allowed=false",
    ),
    "docs/FOUNDATION_DECISION_JOURNAL_BOUNDARY.md": (
        "Foundation Decision Journal Boundary",
        "Witness packet: [`../examples/foundation_decision_journal_witness.awaiting_evidence.json`]",
        "Rule: Decision-journal preparation is a local planning boundary, not a decision-execution, commitment, authority, legal, company, patent, spending, publication, or deployment certificate.",
        "No decision execution, irreversible action, roadmap commitment, deadline",
        "decision_journal_boundary_state=AwaitingEvidence",
        "decision_execution_allowed=false",
        "irreversible_action_allowed=false",
        "roadmap_commitment_claimed=false",
        "deadline_promise_claimed=false",
        "spending_allowed=false",
        "deployment_allowed=false",
    ),
    "docs/FOUNDATION_NEXT_ACTION_BOUNDARY.md": (
        "Foundation Next Action Boundary",
        "Witness packet: [`../examples/foundation_next_action_witness.awaiting_evidence.json`]",
        "Rule: Next-action preparation is a local continuation boundary, not permission",
        "No broad continuation execution, external action, deployment, external",
        "next_action_boundary_state=AwaitingEvidence",
        "broad_continuation_execution_allowed=false",
        "external_action_allowed=false",
        "deployment_allowed=false",
        "spending_allowed=false",
        "source_control_publication_allowed=false",
        "deadline_promise_claimed=false",
        "python scripts/validate_foundation_next_action_boundary.py",
    ),
    "docs/FOUNDATION_TEST_EVIDENCE_BOUNDARY.md": (
        "Foundation Test Evidence Boundary",
        "Witness packet: [`../examples/foundation_test_evidence_witness.awaiting_evidence.json`]",
        "Rule: Test-evidence preparation is a local planning boundary, not a full-test",
        "No full-test-pass, complete-coverage, CI-parity, release-readiness",
        "test_evidence_boundary_state=AwaitingEvidence",
        "full_test_pass_claimed=false",
        "complete_coverage_claimed=false",
        "ci_parity_claimed=false",
        "release_readiness_claimed=false",
        "deployment_readiness_claimed=false",
        "security_clearance_claimed=false",
        "secret_clearance_claimed=false",
        "customer_readiness_claimed=false",
        "legal_clearance_claimed=false",
        "terminal_closure_claimed=false",
        "external_publication_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_test_evidence_boundary.py",
    ),
    "docs/FOUNDATION_PRIVATE_RECOVERY_BOUNDARY.md": (
        "Foundation Private Recovery Boundary",
        "Descriptor: [`../examples/foundation_private_recovery_inventory.redacted.json`]",
        "No secret values are permitted in Git.",
        "Private inventory remains outside this repository.",
        "Do not store recovery codes, passwords, provider account IDs, DNS targets,",
        "Public-safe state is `AwaitingEvidence` until the operator completes the private",
    ),
    "docs/FOUNDATION_SECRETS_CREDENTIALS_BOUNDARY.md": (
        "Foundation Secrets Credentials Boundary",
        "Witness packet: [`../examples/foundation_secrets_credentials_witness.awaiting_evidence.json`]",
        "Rule: Secrets/credentials preparation is a local planning boundary, not permission to store or activate real credentials.",
        "No real-secret storage, credential activation, provider-account binding, API",
        "secrets_credentials_boundary_state=AwaitingEvidence",
        "real_secret_storage_allowed=false",
        "credential_activation_allowed=false",
        "api_key_creation_allowed=false",
        "deployment_allowed=false",
    ),
    "docs/FOUNDATION_SECURITY_BASELINE_BOUNDARY.md": (
        "Foundation Security Baseline Boundary",
        "Witness packet: [`../examples/foundation_security_baseline_witness.awaiting_evidence.json`]",
        "Rule: Security-baseline preparation is a local planning boundary, not",
        "No security baseline verification, secret scan pass, vulnerability scan pass,",
        "security_baseline_boundary_state=AwaitingEvidence",
        "security_baseline_verified=false",
        "secret_scan_pass_claimed=false",
        "vulnerability_scan_pass_claimed=false",
        "deployment_allowed=false",
    ),
    "docs/FOUNDATION_COST_BUDGET_BOUNDARY.md": (
        "Foundation Cost Budget Boundary",
        "Witness packet: [`../examples/foundation_cost_budget_witness.awaiting_evidence.json`]",
        "Rule: Cost/budget preparation is a local planning boundary, not permission to spend money.",
        "No spending authorization, paid infrastructure activation, provider billing",
        "cost_budget_boundary_state=AwaitingEvidence",
        "spending_allowed=false",
        "paid_infrastructure_allowed=false",
        "provider_billing_allowed=false",
        "deployment_allowed=false",
    ),
    "docs/FOUNDATION_PAYMENT_PROVIDER_BOUNDARY.md": (
        "Foundation Payment Provider Boundary",
        "Witness packet: [`../examples/foundation_payment_provider_witness.awaiting_evidence.json`]",
        "Rule: Payment-provider preparation is a local planning boundary, not permission",
        "No payment-provider activation, provider-account binding, merchant-onboarding",
        "payment_provider_boundary_state=AwaitingEvidence",
        "payment_provider_activation_allowed=false",
        "provider_account_binding_allowed=false",
        "merchant_onboarding_claimed=false",
        "kyc_readiness_claimed=false",
        "tax_readiness_claimed=false",
        "payment_method_collection_allowed=false",
        "live_charge_allowed=false",
        "refund_execution_allowed=false",
        "payout_settlement_allowed=false",
        "webhook_activation_allowed=false",
        "checkout_publication_allowed=false",
        "money_movement_allowed=false",
        "customer_payment_access_allowed=false",
        "external_publication_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_payment_provider_boundary.py",
    ),
    "docs/FOUNDATION_RUNTIME_ENVIRONMENT_BOUNDARY.md": (
        "Foundation Runtime Environment Boundary",
        "Witness packet: [`../examples/foundation_runtime_environment_witness.awaiting_evidence.json`]",
        "Rule: Runtime/environment preparation is a local planning boundary, not permission to claim runtime readiness.",
        "No local runtime verification, workstation repeatability verification,",
        "runtime_environment_boundary_state=AwaitingEvidence",
        "local_runtime_verified=false",
        "workstation_repeatability_verified=false",
        "dependency_install_verified=false",
        "deployment_allowed=false",
    ),
    "docs/FOUNDATION_BACKUP_EXPORT_BOUNDARY.md": (
        "Foundation Backup Export Boundary",
        "Witness packet: [`../examples/foundation_backup_export_witness.awaiting_evidence.json`]",
        "Rule: Backup/export preparation is a local planning boundary, not permission to move repository or private data.",
        "No backup execution, cloud backup activation, external export, public archive",
        "backup_export_boundary_state=AwaitingEvidence",
        "backup_execution_allowed=false",
        "cloud_backup_allowed=false",
        "external_export_allowed=false",
        "deployment_allowed=false",
    ),
    "docs/FOUNDATION_DEPLOYMENT_DEFERRAL_BOUNDARY.md": (
        "Foundation Deployment Deferral Boundary",
        "Witness packet: [`../examples/foundation_deployment_deferral_witness.awaiting_evidence.json`]",
        "Rule: Deployment deferral is a local planning boundary, not a deployment plan, production-health certificate, customer-access approval, spending approval, credential-use approval, publication approval, or readiness certificate.",
        "No deployment plan approval, cloud activation, public endpoint, production",
        "deployment_deferral_boundary_state=AwaitingEvidence",
        "deployment_plan_approved=false",
        "cloud_activation_allowed=false",
        "public_endpoint_allowed=false",
        "deployment_allowed=false",
    ),
    "docs/FOUNDATION_EXTERNAL_INFRASTRUCTURE_BOUNDARY.md": (
        "Foundation External Infrastructure Boundary",
        "Witness packet: [`../examples/foundation_external_infrastructure_witness.awaiting_evidence.json`]",
        "Rule: External-infrastructure preparation is a local planning boundary, not an",
        "No external-infrastructure completeness, DNS authority verification, DNS target",
        "external_infrastructure_boundary_state=AwaitingEvidence",
        "external_infrastructure_complete_claimed=false",
        "dns_authority_verified=false",
        "dns_target_bound=false",
        "dns_mutation_allowed=false",
        "runtime_host_provisioned=false",
        "managed_database_provisioned=false",
        "secret_placement_verified=false",
        "endpoint_reachability_claimed=false",
        "repository_variable_binding_allowed=false",
        "workflow_dispatch_allowed=false",
        "paid_infrastructure_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_external_infrastructure_boundary.py",
    ),
    "docs/FOUNDATION_PILOT_DEFERRAL_BOUNDARY.md": (
        "Foundation Pilot Deferral Boundary",
        "Witness packet: [`../examples/foundation_pilot_deferral_witness.awaiting_evidence.json`]",
        "Rule: Pilot deferral is a local planning boundary, not a pilot-execution, participant-invitation, access-opening, market-validation, support-readiness, legal-clearance, paid-pilot, publication, or deployment certificate.",
        "No pilot execution, participant invitation, access channel opening, waitlist",
        "pilot_deferral_boundary_state=AwaitingEvidence",
        "pilot_execution_allowed=false",
        "participant_invitation_allowed=false",
        "access_channel_allowed=false",
        "deployment_allowed=false",
    ),
    "docs/FOUNDATION_DOMAIN_EMAIL_BOUNDARY.md": (
        "Foundation Domain Email Boundary",
        "Witness packet: [`../examples/foundation_domain_email_witness.awaiting_evidence.json`]",
        "Rule: Public identity labels may be recorded, but DNS/email readiness remains",
        "No provider account IDs, private DNS target values, admin-console details,",
        "dns_mutation_allowed=false",
        "api_dns_publication_allowed=false",
        "endpoint_readiness_claimed=false",
        "email_deliverability_claimed=false",
    ),
    "docs/FOUNDATION_PRODUCT_SCOPE_BOUNDARY.md": (
        "Foundation Product Scope Boundary",
        "Witness packet: [`../examples/foundation_product_scope_witness.awaiting_evidence.json`]",
        "Rule: One narrow learning lane is a local proof lane, not a permanent platform restriction.",
        "No pilot access, customer access, market-validation, paid-launch, deployment-readiness,",
        "selected_learning_lane=local_governed_task_receipt",
        "long_term_platform_restricted=false",
        "pilot_access_allowed=false",
        "market_validation_claimed=false",
    ),
    "docs/FOUNDATION_SUPPORT_READINESS_BOUNDARY.md": (
        "Foundation Support Readiness Boundary",
        "Witness packet: [`../examples/foundation_support_readiness_witness.awaiting_evidence.json`]",
        "Rule: Support preparation is a local planning boundary, not a customer-support service.",
        "No customer support opening, support SLA, incident-response readiness, support",
        "customer_support_open=false",
        "support_sla_claimed=false",
        "incident_response_ready_claimed=false",
        "support_mailbox_deliverability_claimed=false",
    ),
    "docs/FOUNDATION_INTAKE_ONBOARDING_BOUNDARY.md": (
        "Foundation Intake Onboarding Boundary",
        "Witness packet: [`../examples/foundation_intake_onboarding_witness.awaiting_evidence.json`]",
        "Rule: Intake preparation is a local planning boundary, not an active intake channel.",
        "No active intake form, waitlist opening, pilot signup, customer onboarding, PII",
        "intake_open=false",
        "waitlist_open=false",
        "pilot_signup_open=false",
        "pii_collection_allowed=false",
    ),
    "docs/FOUNDATION_PRIVACY_DATA_BOUNDARY.md": (
        "Foundation Privacy Data Boundary",
        "Witness packet: [`../examples/foundation_privacy_data_witness.awaiting_evidence.json`]",
        "Rule: Privacy/data preparation is a local planning boundary, not permission to handle personal data.",
        "No personal-data collection, personal-data storage, retention-policy approval,",
        "personal_data_collection_allowed=false",
        "personal_data_storage_allowed=false",
        "retention_policy_approved=false",
        "privacy_notice_published=false",
    ),
    "docs/FOUNDATION_CUSTOMER_ACCESS_BOUNDARY.md": (
        "Foundation Customer Access Boundary",
        "Witness packet: [`../examples/foundation_customer_access_witness.awaiting_evidence.json`]",
        "Rule: Customer-access preparation is a local planning boundary, not an access approval.",
        "No customer access opening, customer invitation, account creation, access-channel",
        "customer_access_boundary_state=AwaitingEvidence",
        "customer_access_allowed=false",
        "customer_invitation_allowed=false",
        "account_creation_allowed=false",
        "access_channel_open_allowed=false",
        "onboarding_ready_claimed=false",
        "support_commitment_allowed=false",
        "terms_privacy_ready_claimed=false",
        "personal_data_collection_allowed=false",
        "paid_access_allowed=false",
        "pilot_access_allowed=false",
        "beta_access_allowed=false",
        "waitlist_open=false",
        "external_publication_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_customer_access_boundary.py",
    ),
    "docs/FOUNDATION_LEGAL_BUSINESS_BOUNDARY.md": (
        "Foundation Legal Business Boundary",
        "Question packet: [`../examples/foundation_legal_business_questions.awaiting_review.json`]",
        "Rule: Legal and business readiness stays `AwaitingEvidence` until qualified",
        "No legal clearance, company readiness, patent protection, trademark clearance,",
        "paid_launch_allowed=false",
        "money_movement_allowed=false",
    ),
    "docs/FOUNDATION_COMMUNITY_NETWORK_BOUNDARY.md": (
        "Foundation Community Network Boundary",
        "Witness packet: [`../examples/foundation_community_network_witness.awaiting_evidence.json`]",
        "Rule: Community/network preparation is a local planning boundary, not outreach, recruiting, public feedback, partnership, or publication.",
        "No community outreach, social post publication, forum post publication, direct",
        "community_network_boundary_state=AwaitingEvidence",
        "community_outreach_allowed=false",
        "social_post_publication_allowed=false",
        "forum_post_publication_allowed=false",
        "direct_message_allowed=false",
        "collaborator_recruitment_allowed=false",
        "partnership_outreach_allowed=false",
        "mentor_request_allowed=false",
        "public_feedback_request_allowed=false",
        "event_participation_allowed=false",
        "contact_list_recorded=false",
        "personal_data_collection_allowed=false",
        "external_account_use_allowed=false",
        "public_profile_claimed=false",
        "customer_access_allowed=false",
        "external_publication_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_community_network_boundary.py",
    ),
    "docs/FOUNDATION_FUNDING_TEAM_BOUNDARY.md": (
        "Foundation Funding Team Boundary",
        "Witness packet: [`../examples/foundation_funding_team_witness.awaiting_evidence.json`]",
        "Rule: Funding/team preparation is a local planning boundary, not fundraising, hiring, or team formation.",
        "No fundraising, investor outreach, grant application, pitch publication, hiring,",
        "funding_team_boundary_state=AwaitingEvidence",
        "fundraising_allowed=false",
        "investor_outreach_allowed=false",
        "grant_application_allowed=false",
        "pitch_deck_publication_allowed=false",
        "hiring_allowed=false",
        "contractor_engagement_allowed=false",
        "advisor_commitment_allowed=false",
        "compensation_commitment_allowed=false",
        "equity_promise_allowed=false",
        "payroll_setup_allowed=false",
        "budget_commitment_allowed=false",
        "company_formation_claimed=false",
        "legal_clearance_claimed=false",
        "money_movement_allowed=false",
        "external_publication_allowed=false",
        "deployment_allowed=false",
        "python scripts/validate_foundation_funding_team_boundary.py",
    ),
    "docs/START_HERE.md": (
        "[Foundation Prerequisites](FOUNDATION_PREREQUISITES.md)",
        "[Foundation Operator Readiness Boundary](FOUNDATION_OPERATOR_READINESS_BOUNDARY.md)",
        "[Foundation Learning Path Boundary](FOUNDATION_LEARNING_PATH_BOUNDARY.md)",
        "[Foundation Architecture Map Boundary](FOUNDATION_ARCHITECTURE_MAP_BOUNDARY.md)",
        "[Foundation System Boundary Inventory Boundary](FOUNDATION_SYSTEM_BOUNDARY_INVENTORY_BOUNDARY.md)",
        "[Foundation Module Inventory Boundary](FOUNDATION_MODULE_INVENTORY_BOUNDARY.md)",
        "[Foundation Component Contract Boundary](FOUNDATION_COMPONENT_CONTRACT_BOUNDARY.md)",
        "[Foundation Interface Map Boundary](FOUNDATION_INTERFACE_MAP_BOUNDARY.md)",
        "[Foundation Dependency Graph Boundary](FOUNDATION_DEPENDENCY_GRAPH_BOUNDARY.md)",
        "[Foundation Invariant Map Boundary](FOUNDATION_INVARIANT_MAP_BOUNDARY.md)",
        "[Foundation Hazard Map Boundary](FOUNDATION_HAZARD_MAP_BOUNDARY.md)",
        "[Foundation Proof Reference Boundary](FOUNDATION_PROOF_REFERENCE_BOUNDARY.md)",
        "[Foundation Gap Register Boundary](FOUNDATION_GAP_REGISTER_BOUNDARY.md)",
        "[Foundation Diff Review Boundary](FOUNDATION_DIFF_REVIEW_BOUNDARY.md)",
        "[Foundation Change Handoff Boundary](FOUNDATION_CHANGE_HANDOFF_BOUNDARY.md)",
        "[Foundation Local Workstation Boundary](FOUNDATION_LOCAL_WORKSTATION_BOUNDARY.md)",
        "[Foundation Documentation Boundary](FOUNDATION_DOCUMENTATION_BOUNDARY.md)",
        "[Foundation Plain-Language Status Boundary](FOUNDATION_PLAIN_LANGUAGE_STATUS_BOUNDARY.md)",
        "[Foundation Claim Boundary](FOUNDATION_CLAIM_BOUNDARY.md)",
        "[Foundation Website Posture Boundary](FOUNDATION_WEBSITE_POSTURE_BOUNDARY.md)",
        "[Foundation Research Notebook Boundary](FOUNDATION_RESEARCH_NOTEBOOK_BOUNDARY.md)",
        "[Foundation Evidence Ledger Boundary](FOUNDATION_EVIDENCE_LEDGER_BOUNDARY.md)",
        "[Foundation Decision Journal Boundary](FOUNDATION_DECISION_JOURNAL_BOUNDARY.md)",
        "[Foundation Next Action Boundary](FOUNDATION_NEXT_ACTION_BOUNDARY.md)",
        "[Foundation Test Evidence Boundary](FOUNDATION_TEST_EVIDENCE_BOUNDARY.md)",
        "[Foundation Source Control Boundary](FOUNDATION_SOURCE_CONTROL_BOUNDARY.md)",
        "[Foundation Local Proof Thread](FOUNDATION_LOCAL_PROOF_THREAD.md)",
        "[Foundation Secrets Credentials Boundary](FOUNDATION_SECRETS_CREDENTIALS_BOUNDARY.md)",
        "[Foundation Security Baseline Boundary](FOUNDATION_SECURITY_BASELINE_BOUNDARY.md)",
        "[Foundation Cost Budget Boundary](FOUNDATION_COST_BUDGET_BOUNDARY.md)",
        "[Foundation Payment Provider Boundary](FOUNDATION_PAYMENT_PROVIDER_BOUNDARY.md)",
        "[Foundation Runtime Environment Boundary](FOUNDATION_RUNTIME_ENVIRONMENT_BOUNDARY.md)",
        "[Foundation Backup Export Boundary](FOUNDATION_BACKUP_EXPORT_BOUNDARY.md)",
        "[Foundation Deployment Deferral Boundary](FOUNDATION_DEPLOYMENT_DEFERRAL_BOUNDARY.md)",
        "[Foundation External Infrastructure Boundary](FOUNDATION_EXTERNAL_INFRASTRUCTURE_BOUNDARY.md)",
        "[Foundation Pilot Deferral Boundary](FOUNDATION_PILOT_DEFERRAL_BOUNDARY.md)",
        "[Foundation Private Recovery Boundary](FOUNDATION_PRIVATE_RECOVERY_BOUNDARY.md)",
        "[Foundation Domain Email Boundary](FOUNDATION_DOMAIN_EMAIL_BOUNDARY.md)",
        "[Foundation Product Scope Boundary](FOUNDATION_PRODUCT_SCOPE_BOUNDARY.md)",
        "[Foundation Support Readiness Boundary](FOUNDATION_SUPPORT_READINESS_BOUNDARY.md)",
        "[Foundation Intake Onboarding Boundary](FOUNDATION_INTAKE_ONBOARDING_BOUNDARY.md)",
        "[Foundation Privacy Data Boundary](FOUNDATION_PRIVACY_DATA_BOUNDARY.md)",
        "[Foundation Customer Access Boundary](FOUNDATION_CUSTOMER_ACCESS_BOUNDARY.md)",
        "[Foundation Legal Business Boundary](FOUNDATION_LEGAL_BUSINESS_BOUNDARY.md)",
        "[Foundation Funding Team Boundary](FOUNDATION_FUNDING_TEAM_BOUNDARY.md)",
        "[Foundation Community Network Boundary](FOUNDATION_COMMUNITY_NETWORK_BOUNDARY.md)",
        "what to prepare now, what to delay, and what evidence to keep",
    ),
    "docs/CURRENT_READINESS_SNAPSHOT.md": (
        "Prerequisite ledger",
        "`docs/FOUNDATION_PREREQUISITES.md`",
        "`docs/FOUNDATION_OPERATOR_READINESS_BOUNDARY.md`",
        "`docs/FOUNDATION_LEARNING_PATH_BOUNDARY.md`",
        "`docs/FOUNDATION_ARCHITECTURE_MAP_BOUNDARY.md`",
        "`docs/FOUNDATION_SYSTEM_BOUNDARY_INVENTORY_BOUNDARY.md`",
        "`docs/FOUNDATION_MODULE_INVENTORY_BOUNDARY.md`",
        "`docs/FOUNDATION_COMPONENT_CONTRACT_BOUNDARY.md`",
        "`docs/FOUNDATION_INTERFACE_MAP_BOUNDARY.md`",
        "`docs/FOUNDATION_DEPENDENCY_GRAPH_BOUNDARY.md`",
        "`docs/FOUNDATION_INVARIANT_MAP_BOUNDARY.md`",
        "`docs/FOUNDATION_HAZARD_MAP_BOUNDARY.md`",
        "`docs/FOUNDATION_PROOF_REFERENCE_BOUNDARY.md`",
        "`docs/FOUNDATION_GAP_REGISTER_BOUNDARY.md`",
        "`docs/FOUNDATION_DIFF_REVIEW_BOUNDARY.md`",
        "`docs/FOUNDATION_CHANGE_HANDOFF_BOUNDARY.md`",
        "`docs/FOUNDATION_LOCAL_WORKSTATION_BOUNDARY.md`",
        "`docs/FOUNDATION_DOCUMENTATION_BOUNDARY.md`",
        "`docs/FOUNDATION_PLAIN_LANGUAGE_STATUS_BOUNDARY.md`",
        "`docs/FOUNDATION_CLAIM_BOUNDARY.md`",
        "`docs/FOUNDATION_WEBSITE_POSTURE_BOUNDARY.md`",
        "`docs/FOUNDATION_RESEARCH_NOTEBOOK_BOUNDARY.md`",
        "`docs/FOUNDATION_EVIDENCE_LEDGER_BOUNDARY.md`",
        "`docs/FOUNDATION_DECISION_JOURNAL_BOUNDARY.md`",
        "`docs/FOUNDATION_NEXT_ACTION_BOUNDARY.md`",
        "`docs/FOUNDATION_TEST_EVIDENCE_BOUNDARY.md`",
        "`docs/FOUNDATION_SECRETS_CREDENTIALS_BOUNDARY.md`",
        "`docs/FOUNDATION_SECURITY_BASELINE_BOUNDARY.md`",
        "`docs/FOUNDATION_COST_BUDGET_BOUNDARY.md`",
        "`docs/FOUNDATION_PAYMENT_PROVIDER_BOUNDARY.md`",
        "`docs/FOUNDATION_RUNTIME_ENVIRONMENT_BOUNDARY.md`",
        "`docs/FOUNDATION_BACKUP_EXPORT_BOUNDARY.md`",
        "`docs/FOUNDATION_DEPLOYMENT_DEFERRAL_BOUNDARY.md`",
        "`docs/FOUNDATION_EXTERNAL_INFRASTRUCTURE_BOUNDARY.md`",
        "`docs/FOUNDATION_PILOT_DEFERRAL_BOUNDARY.md`",
        "`docs/FOUNDATION_CUSTOMER_ACCESS_BOUNDARY.md`",
        "`docs/FOUNDATION_FUNDING_TEAM_BOUNDARY.md`",
        "`docs/FOUNDATION_COMMUNITY_NETWORK_BOUNDARY.md`",
    ),
    "docs/explain/PLAIN_ENGLISH.md": (
        "Current foundation posture",
        "[Foundation Mode](../FOUNDATION_MODE.md)",
        "[Foundation Plain-Language Status Boundary](../FOUNDATION_PLAIN_LANGUAGE_STATUS_BOUNDARY.md)",
        "future governed",
        "The safe work now is local proof",
        "Nothing on this page claims public launch, customer access, legal clearance,",
        "Those are product-direction examples, not current customer access claims.",
        "Foundation Mode keeps them local until the required witnesses exist.",
    ),
    "docs/WEBSITE_UPDATE_CHECKLIST.md": (
        "Foundation-stage proof-boundary action only until clearance and witness gates close",
        "foundation-stage with no access, waitlist, or beta invitation",
    ),
    "docs/WEBSITE_DEPLOYMENT_EVIDENCE_TEMPLATE.md": (
        "foundation_boundary_only",
        "foundation-stage with no access, waitlist, or beta invitation",
    ),
    "docs/PUBLIC_NAMING_REVIEW_PACKET.md": (
        "foundation-stage with no access, waitlist, or beta invitation",
        "Paid public launch allowed | false",
    ),
    "docs/PUBLIC_NAMING_READINESS.md": (
        "foundation-stage proof-boundary copy with no access, waitlist, or",
        "beta invitation, not a paid public launch page",
    ),
    "scripts/plan_public_naming_transition.py": (
        "foundation-stage proof-boundary copy with no access invitation",
    ),
    "site/mullu/index.html": (
        "foundation mode",
        "local proof first",
        "deployment and customer access are not claimed",
    ),
    "site/proof/index.html": (
        "Public deployment",
        "customer access are not claimed",
        "Public launch remains blocked",
        "runtime witness evidence close",
    ),
}

FORWARD_LOOKING_FILES = tuple(REQUIRED_PHRASES_BY_FILE)

FORBIDDEN_FORWARD_PHRASES = (
    "Request access",
    "request access until",
    "request-access until",
    "Start pilot",
    "pilot access is open",
    "private beta access",
    "foundation-stage, waitlist",
    "foundation-stage, private beta",
    "waitlist/private beta",
    "private_beta_only",
    "customer access is open",
    "production-ready",
    "live endpoint",
    "deployed runtime",
    "public sandbox is available",
)


@dataclass(frozen=True, slots=True)
class FoundationModeFinding:
    """One deterministic Foundation Mode validation finding."""

    rule_id: str
    message: str


def read_required_text(repo_root: Path, relative_path: str) -> str:
    """Read one required repository file with explicit path errors."""

    path = repo_root / relative_path
    if not path.exists():
        raise FileNotFoundError(f"missing Foundation Mode file: {relative_path}")
    if not path.is_file():
        raise IsADirectoryError(f"Foundation Mode path is not a file: {relative_path}")
    return path.read_text(encoding="utf-8")


def validate_required_phrases(repo_root: Path = REPO_ROOT) -> list[FoundationModeFinding]:
    """Return findings for missing current-posture anchor phrases."""

    findings: list[FoundationModeFinding] = []
    for relative_path, required_phrases in REQUIRED_PHRASES_BY_FILE.items():
        try:
            text = read_required_text(repo_root, relative_path)
        except OSError as exc:
            findings.append(FoundationModeFinding("foundation_file_missing", str(exc)))
            continue
        for phrase in required_phrases:
            if phrase not in text:
                findings.append(
                    FoundationModeFinding(
                        "foundation_phrase_missing",
                        f"{relative_path} missing required phrase: {phrase}",
                    )
                )
    return findings


def validate_forward_text_boundary(
    relative_path: str,
    text: str,
    forbidden_phrases: tuple[str, ...] = FORBIDDEN_FORWARD_PHRASES,
) -> list[FoundationModeFinding]:
    """Return findings when current guidance authorizes blocked access language."""

    lowered_text = text.casefold()
    findings: list[FoundationModeFinding] = []
    for phrase in forbidden_phrases:
        if phrase.casefold() in lowered_text:
            findings.append(
                FoundationModeFinding(
                    "foundation_forbidden_forward_phrase",
                    f"{relative_path} contains forward-looking blocked phrase: {phrase}",
                )
            )
    return findings


def validate_forbidden_forward_phrases(repo_root: Path = REPO_ROOT) -> list[FoundationModeFinding]:
    """Return findings for blocked phrases in current-posture files."""

    findings: list[FoundationModeFinding] = []
    for relative_path in FORWARD_LOOKING_FILES:
        try:
            text = read_required_text(repo_root, relative_path)
        except OSError as exc:
            findings.append(FoundationModeFinding("foundation_file_missing", str(exc)))
            continue
        findings.extend(validate_forward_text_boundary(relative_path, text))
    return findings


def validate_foundation_mode(repo_root: Path = REPO_ROOT) -> list[FoundationModeFinding]:
    """Validate the repository Foundation Mode posture and return findings."""

    return [
        *validate_required_phrases(repo_root),
        *validate_forbidden_forward_phrases(repo_root),
    ]


def main(argv: list[str] | None = None) -> int:
    """Validate Foundation Mode and print a deterministic status."""

    parser = argparse.ArgumentParser(description="Validate Mullusi Foundation Mode posture.")
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    args = parser.parse_args(argv)

    findings = validate_foundation_mode(args.repo_root.resolve())
    if findings:
        for finding in findings:
            print(f"[FAIL] {finding.rule_id}: {finding.message}", file=sys.stderr)
        print("STATUS: failed", file=sys.stderr)
        return 1
    print("STATUS: passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
